### ISSUE TITLE
Edit on PythonNode not working on Python 3.10 or 3.8

### ISSUE THREAD

**Issue by mastermind88** [pedroCabrera/PyFlow#116]
Every time I try to edit a generic pythonNode code, nothing shows up. Console error log:

```
Traceback (most recent call last):
   File "C:\PyFlow\PyFlow\Packages\PyFlowBase\UI\UIPythonNode.py", line 190, in onEdit
      tempFilesDir = self.canvasRef().getApp().getTempDirectory()
   File "C:\PyFlow\PyFlow\App.py", line 169, in getTempDirectory
      if tempDirPath[-1:] in ('/', '\\'):
TypeError: 'NoneType' object is not subscriptable
```

Tried both actual master and latest release branch, with both 3.10 and 3.8 Python version on Windows 10 and Linux environments.

**Comment by mastermind88** [comment]
The issue look was due to an invalid default temp folder with incorrect write access. Once set manually on preferences a different folder the issue have been fixed.
