### ISSUE TITLE
pyflow.exe on Windows won't start

### ISSUE THREAD

**Issue by wassimj** [pedroCabrera/PyFlow#130]
I just pip install PyFlow on Windows 11, but when I issue the command pyflow.exe, I get the following error:
```
C:\Users\wassimj>pyflow.exe
Traceback (most recent call last):
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\Scripts\pyflow.exe\__main__.py", line 7, in <module>
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\site-packages\PyFlow\Scripts\__init__.py", line 71, in main
    instance = PyFlow.instance(software="standalone")
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\site-packages\PyFlow\App.py", line 623, in instance
    instance = PyFlow(parent)
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\site-packages\PyFlow\App.py", line 105, in __init__
    self.canvasWidget = BlueprintCanvasWidget(self.graphManager.get(), self)
  File "C:\Users\wassimj\AppData\Local\Programs\Python\Python310\lib\site-packages\PyFlow\UI\Widgets\BlueprintCanvas.py", line 2041, in __init__
    self.mainLayout.addLayout(self.pathLayout)
TypeError: 'PySide6.QtWidgets.QBoxLayout.addLayout' called with wrong argument types:
  PySide6.QtWidgets.QBoxLayout.addLayout(QHBoxLayout)
Supported signatures:
  PySide6.QtWidgets.QBoxLayout.addLayout(PySide6.QtWidgets.QLayout, int = 0)

C:\Users\wassimj>
```

**Comment by pedroCabrera** [comment]
I cant reproduce this isue, are you runing it from a pip install or did you cloned the repo?
What versIon of pyside are you using? in a clean install with python 3 pip install -r requirements.txt its working here in windows, using pyside6 and master branch ( release branch wasnt up to date, it is now )

**Comment by pedroCabrera** [comment]
I cant reproduce this isue, are you runing it from a pip install or did you cloned the repo?
What versIon of pyside are you using? in a clean install with python 3 pip install -r requirements.txt its working here in windows, using pyside6 and master branch ( release branch wasnt up to date, it is now )
