### ISSUE TITLE
Exporting a custom PythonNode as a .py is not working.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#3]
I tested the Export function and when I tried to save a PythonNode with custom code as a .py to use it later as a Custom Node I got this error:

```
Traceback (most recent call last):
  File "C:\Users\ZeroCool940711\Desktop\PyFlow\PyFlow-master\PyFlow\Nodes\pythonNode.py", line 110, in export
    self._implementPlugin(self.name,portString,foo)
  File "C:\Users\ZeroCool940711\Desktop\PyFlow\PyFlow-master\PyFlow\Nodes\pythonNode.py", line 138, in _implementPlugin
    path,name = os.path.split(file_path)
  File "D:\Python\lib\ntpath.py", line 180, in split
    d, p = splitdrive(p)
  File "D:\Python\lib\ntpath.py", line 116, in splitdrive
    normp = p.replace(altsep, sep)
AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by pedroCabrera** [comment]
Fixed ! working both pyqt4 and pyside2
