### ISSUE TITLE
Triple quote comments inside a PythoNode error.

### ISSUE THREAD

**Issue by ZeroCool940711** [pedroCabrera/PyFlow#31]
When using comments inside a PythoNode using triple quotes doesn't matter if its `triple single quote` or `triple double quotes` you'll get the following error:

```
Traceback (most recent call last):
  File "C:\Users\ZeroCool940711\Desktop\PyFlow\PyFlow\Core\PythonSyntax.py", line 137, in highlightBlock
    in_multiline = self.match_multiline(text, *self.tri_double)
  File "C:\Users\ZeroCool940711\Desktop\PyFlow\PyFlow\Core\PythonSyntax.py", line 167, in match_multiline
    length = text.length() - start + add
AttributeError: 'unicode' object has no attribute 'length'
```

Been able to have multiline comments inside a PythonNode is a must as its really common to use them.

**Comment by IlgarLunin** [comment]
Now we use external editor. So I'll close this
