### ISSUE TITLE
issue creating compound by collapsing

### ISSUE THREAD

**Issue by looooo** [pedroCabrera/PyFlow#54]
1. I had to click ctrl to show the corresponding menu on right click. Not sure if this is wanted.
2. There is a traceback printed and the collapsed node is missing the pins.

```
[ERROR 16:37:55]: 'NoneType' object has no attribute 'description'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 352, in mainLoop
self.graphManager.get().Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphManager.py", line 141, in Tick
graph.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphBase.py", line 278, in Tick
node.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 97, in Tick
self.syncPins()
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 71, in syncPins
self.onGraphInputPinCreated(outPin)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 158, in onGraphInputPinCreated
self.pinExposed.send(subgraphInputPin)
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in send
for receiver in self.receivers_for(sender)]
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in 
for receiver in self.receivers_for(sender)]
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1386, in _createUIPinWrapper
grpItem = PinGroup(self, rawPin.direction, rawPin.group)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 434, in __init__
super(PinGroup, self).__init__(owningNode, None)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 120, in __init__
self.setToolTip(self._rawPin.description)
AttributeError: 'NoneType' object has no attribute 'description'
[ERROR 16:37:55]: 'PinGroup' object has no attribute 'expanded'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 555, in paint
if not self.expanded:
AttributeError: 'PinGroup' object has no attribute 'expanded'
[ERROR 16:37:55]: 'NoneType' object has no attribute 'description'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 352, in mainLoop
self.graphManager.get().Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphManager.py", line 141, in Tick
graph.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphBase.py", line 278, in Tick
node.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 97, in Tick
self.syncPins()
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 71, in syncPins
self.onGraphInputPinCreated(outPin)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 158, in onGraphInputPinCreated
self.pinExposed.send(subgraphInputPin)
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in send
for receiver in self.receivers_for(sender)]
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in 
for receiver in self.receivers_for(sender)]
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1386, in _createUIPinWrapper
grpItem = PinGroup(self, rawPin.direction, rawPin.group)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 434, in __init__
super(PinGroup, self).__init__(owningNode, None)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 120, in __init__
self.setToolTip(self._rawPin.description)
AttributeError: 'NoneType' object has no attribute 'description'
[ERROR 16:37:55]: 'PinGroup' object has no attribute 'expanded'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 555, in paint
if not self.expanded:
AttributeError: 'PinGroup' object has no attribute 'expanded'
[ERROR 16:37:55]: 'NoneType' object has no attribute 'description'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/App.py", line 352, in mainLoop
self.graphManager.get().Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphManager.py", line 141, in Tick
graph.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Core/GraphBase.py", line 278, in Tick
node.Tick(deltaTime)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 97, in Tick
self.syncPins()
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 80, in syncPins
self.onGraphOutputPinCreated(inPin)
File "/home/k/projects/PyFlow/PyFlow/Packages/PyFlowBase/Nodes/compound.py", line 197, in onGraphOutputPinCreated
self.pinExposed.send(subgraphOutputPin)
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in send
for receiver in self.receivers_for(sender)]
File "/home/k/conda/envs/pyflow3/lib/python3.7/site-packages/blinker/base.py", line 267, in 
for receiver in self.receivers_for(sender)]
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UINodeBase.py", line 1392, in _createUIPinWrapper
grpItem = PinGroup(self, rawPin.direction, rawPin.group)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 434, in __init__
super(PinGroup, self).__init__(owningNode, None)
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 120, in __init__
self.setToolTip(self._rawPin.description)
AttributeError: 'NoneType' object has no attribute 'description'
[ERROR 16:37:55]: 'PinGroup' object has no attribute 'expanded'
Traceback (most recent call last):
File "/home/k/projects/PyFlow/PyFlow/UI/Canvas/UIPinBase.py", line 555, in paint
if not self.expanded:
AttributeError: 'PinGroup' object has no attribute 'expanded'
```

**Comment by looooo** [comment]
similar on windows, but without traceback:
![before](https://user-images.githubusercontent.com/5084704/62378338-e4a60580-b544-11e9-9a6c-ae4ccf44a855.PNG)
![after](https://user-images.githubusercontent.com/5084704/62378341-e66fc900-b544-11e9-8ab0-1b20aaf86860.PNG)

**Comment by IlgarLunin** [comment]
Ok, will check it also. Thanks

**Comment by looooo** [comment]
thanks, works:
![Bildschirmfoto von 2019-08-03 10-51-14](https://user-images.githubusercontent.com/5084704/62409782-aa884280-b5dc-11e9-94fb-d2984e20cac5.png)

**Comment by IlgarLunin** [comment]
Problem was because of GroupPin. it has no underlined raw pin as well as description. I'll improve this section of program later, for not it will work
