### ISSUE TITLE
Can't run in Windows

### ISSUE THREAD

**Issue by Sup3rGeo** [pedroCabrera/PyFlow#8]
Hi,

Apparently there is no `PySide2` python 2.7 for windows. I can install `PySide`, but running running your app I get an exception:

```
C:\Users\victo\PycharmProjects\PyFlow>py -2 C:\Users\victo\PycharmProjects\PyFlow/launcher.py
(ImportError('No module named pyrr',), 'FloatVector3Pin')
(ImportError('No module named pyrr',), 'FloatVector4Pin')
(ImportError('No module named pyrr',), 'Matrix33Pin')
(ImportError('No module named pyrr',), 'Matrix44Pin')
(ImportError('No module named pyrr',), 'QuatPin')
Traceback (most recent call last):
  File "C:\Users\victo\PycharmProjects\PyFlow/launcher.py", line 6, in <module>
    from PyFlow.App import PyFlow
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\App.py", line 15, in <module>
    from Core.Widget import GraphWidget
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\Core\__init__.py", line 8, in <module>
    from Node import Node
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\Core\Node.py", line 26, in <module>
    from .InputWidgets import getInputWidget
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\Core\InputWidgets.py", line 18, in <module>
    from ..UI import FloatVector3InputWidget_ui
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\UI\FloatVector3InputWidget_ui.py", line 93, in <module>
    import nodes_res_rc
  File "C:\Users\victo\PycharmProjects\PyFlow\PyFlow\UI\nodes_res_rc.py", line 10, in <module>
    from PySide2 import QtCore
ImportError: No module named PySide2
```

So although in the readme it says pyside or pyside2, it appears it is still asking explicitly for pyside2.
I guess this would be naturally solved with #3.

Thanks.

**Comment by IlgarLunin** [comment]
Hi,

The problem occurs because of pyside2-uic generated files. I'll fix this as soon as possible, tnx
